package com.cafe.modelo;

public enum Tipo {

	ABANADOR_CEREAL,
	ADUBADORA_AUTOPROPELIDA,
	APLICADOR_AUTOPROPELIDO,
	ATOMIZADOR_COSTAL_MOTORIZADO,
	BATEDEIRA_CEREAIS,
	BENEFICIADORA,
	CAMINHAO,
	CAPINADEIRA,
	CARREGADORA_AGRICOLA_CANA,
	COLHEDORA,
	COLHEDORA_AUTOPROPELIDA_MINICEIFA,
	CULTIVADOR_MOTORIZADO_GRAOS_CEREAIS,
	DEBULHADEIRA,
	DESINTEGRADOR,
	ENSILADEIRA
}
