package com.cafe.modelo.enums;

/**
 * @author isabella
 *
 */

public enum TipoAuxiliarInsumos {
	
	/* ---------------------------------*/
	/* tipos de maquinas   */
	/* ---------------------------------*/
	ABANADOR_CEREAL,
	ADUBADORA_AUTOPROPELIDA,
	APLICADOR_AUTOPROPELIDO,
	ARRUADORA,
	ATOMIZADOR_COSTAL_MOTORIZADO,
	BATEDEIRA_CEREAIS,
	BENEFICIADORA,
	CAMINHAO,
	CANHAO_PULVERIZACAO,
	CAPINADEIRA,
	CARREGADORA_AGRICOLA_CANA,
	CARRETA,
	COLHEDORA,
	COLHEDORA_AUTOPROPELIDA_MINICEIFA,
	SEPARADOR_HIDRAULICO_CAFE,
	SOPRADOR,
	SUBSOLADOR,
	TRATOR,
	TRINCHA,
	TRITURADORES,
	
	/* ---------------------------------*/
	/* tipos de implementos   */
	/* ---------------------------------*/
	CULTIVADOR_MOTORIZADO_GRAOS_CEREAIS,
	DESMUCILADOR,
	DEBULHADEIRA,
	DERRICADEIRA,
	DESINTEGRADOR,
	DESPOLPADOR,
	ENSILADEIRA,
	GRADE,
	PODADOR,
	RECOLHEDOR,
	ROCADEIRA,
	ROCADEIRA_TRATORIZADA,
	SECADOR_ESTATICO,
	SECADOR_HORIZONTAL,
	SECADOR_LEITO_FIXO,
	
	
	
	/* ---------------------------------*/
	/* tipos de fertilizantes   */
	/* ---------------------------------*/
	ACIDO_BORICO,
	BORAX,
	CALCARIO,
	CLORETO_DE_POTASSIO,
	FOSFATO_DIAMONICO_DAP,
	FOSFATO_MONOAMONICO_MAP,
	FOSFATO_NATURAL,
	NITRATO_DE_AMONIO,
	NITRATO_DE_CALCIO,
	OXIDO_CUPROSO,
	SULFATO_DE_AMONIO,
	SULFATO_DE_CALCIO,
	SULFATO_DE_COBRE,
	SULFATO_DE_ZINCO,
	SULFATO_MANGANOSO,
	SUPER_FOSFATO_SIMPLES,
	SUPERFOSFATO_DUPLO,
	SUPERFOSFATO_TRIPLO,
	TERMOFOSFATO,
	UREIA,
	UREIA_FORMALDEIDO,
	NPK_10_10_10,
	NPK_20_00_20,
	NPK_20_05_20,
	NPK_30_00_10,
	NPK_30_00_20,
	
	/* ---------------------------------*/
	/* tipos de defensivos   */
	/* ---------------------------------*/
	DEFENSIVO
}
