package com.cafe.modelo.enums;

public enum TipoCusteioOutros {
	OPERACAO_ANIMAL,
	OPERACAO_AVIAO,
	ALUGUEL_MAQUINAS,
	ALUGUEL_ANIMAIS,
	MAO_DE_OBRA,
	ADMINISTRADOR,
	SEMENTES_E_MUDAS,
	EMBALAGENS_UTENSILIOS,
	ANALISE_DE_SOLO,
	DEMAIS_DESPESAS,
	SERVICOS_DIVERSOS,
	OUTROS;
}
