package com.cafe.modelo.enums;

/**
 * @author isabella
 *
 */

public enum TipoAuxiliarInsumos {
	
	
	/* ---------------------------------*/
	/* tipos de fertilizantes   */
	/* ---------------------------------*/
	ACIDO_BORICO,
	BORAX,
	CALCARIO,
	CLORETO_DE_POTASSIO,
	FOSFATO_DIAMONICO_DAP,
	FOSFATO_MONOAMONICO_MAP,
	FOSFATO_NATURAL,
	NITRATO_DE_AMONIO,
	NITRATO_DE_CALCIO,
	OXIDO_CUPROSO,
	SULFATO_DE_AMONIO,
	SULFATO_DE_CALCIO,
	SULFATO_DE_COBRE,
	SULFATO_DE_ZINCO,
	SULFATO_MANGANOSO,
	SUPER_FOSFATO_SIMPLES,
	SUPERFOSFATO_DUPLO,
	SUPERFOSFATO_TRIPLO,
	TERMOFOSFATO,
	UREIA,
	UREIA_FORMALDEIDO,
	NPK_10_10_10,
	NPK_20_00_20,
	NPK_20_05_20,
	NPK_30_00_10,
	NPK_30_00_20,
	OUTROS,
	
	/* ---------------------------------*/
	/* tipos de fungicidas   */
	/* ---------------------------------*/
	
	ALIETTE_WP,
	ALTO_100_CONCENTRADO_SOLUVEL_SL,
	AMISTAR_WG_ESTROBIRULINA,
	APROACH_POWER_CONCENTRADO_EMULSIONAVEL,
	APROACH_PRIMA_SC,
	BIO_IMUNE_SC,
	CANTUS_WG_VIVEIRO,
	COMET_EC_ESTROBIRULINA,
	CUPROGARD_350_PO_MOLHAVEL_WP,
	CUPROZEB_WP_DITIOCARBAMATO,
	ELITE_200_EC,
	FEGATEX_SL,
	FLEXIN_SC,
	FOLICUR_200_EC,
	GARANT_BR_WP_VIVEIRO,
	IMPACT_125_SC,
	KASUMIN,
	NATIVO_SC_TRIFLOXISTROBINA,
	OPERA_SUSPOEMULSAO_SE,
	ORKESTRA_SC,
	PREMIER_PLUS_SC,
	PRIORI_TOP_SC,
	PRIORI_XTRA_SC,
	RECOP_WP,
	ROVRAL_SC,
	ROVRAL_WP,
	SERENADE,
	SIMBOLL_125_SC,
	SPHERE_MAX_SC,
	TENAZ_250_SC,
	VERDADERO_600_WG,
	
	
	/* ---------------------------------*/
	/* tipos de inseticidas   */
	/* ---------------------------------*/
	
	VERISMO_SC,
	SPERTO_WG,
	VOLIAM_TARGO_SC,
	BENEVIA_DISPERSAO_OLEO_OD,
	DURIVO_SC,
	ENVIDOR_SC,
	OBERON_240_SC,
	ABAMECTIN_NORTOX_EC,
	VERTIMEC_18_EC,
	TURBO_EC,
	TALENTO_500_WP,
	ALTACOR_350_WG,
	POLYTRIN_EC,
	ASSIST,
	NIMBUS_IHAROL_ASSIST,
	AGRAL_NONIL_FENOXI_POLI_ETANOL,

	/* ---------------------------------*/
	/* tipos de herbicidas   */
	/* ---------------------------------*/
	
	GOAL_BR_EC_CONCENTRADO_EMULSIONAVEL,
	FLUMYZIN_500_WP,
	DIURON_NORTOX_800_WP_PO_MOLHAVEL,
	ALION_500_SC,
	SULFENTRAZONE_500_SC_P,
	SELECT_240_EC,
	HEAT_700_WG,
	ACCURATE_600_WG,
	CLORIMURON_MASTER_250_WG,
	AURORA_400_EC,
	GLIFOSATO_NORTOX_480_CONCENTRADO_SOLUVEL_SL,
	
	/* ---------------------------------*/
	/* tipos de adjuvantes   */
	/* ---------------------------------*/
	VEGETAL,
	MINERAL

}
